// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWVU6-oOnOLE_2nVjelRf0DrHudzlffc',
    appId: '1:215663281164:web:4c05836152a1135cfd1a29',
    messagingSenderId: '215663281164',
    projectId: 'riverpod-firestore-stream1',
    authDomain: 'riverpod-firestore-stream1.firebaseapp.com',
    storageBucket: 'riverpod-firestore-stream1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Pf5oMUisZqXVe9_iqgG5aBvUj3V7cRc',
    appId: '1:215663281164:android:53f6553f12cc7ebafd1a29',
    messagingSenderId: '215663281164',
    projectId: 'riverpod-firestore-stream1',
    storageBucket: 'riverpod-firestore-stream1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9EHtWIbuBjIgGFwo33f6Va_uERsjXq2M',
    appId: '1:215663281164:ios:11480aabf80ff6ddfd1a29',
    messagingSenderId: '215663281164',
    projectId: 'riverpod-firestore-stream1',
    storageBucket: 'riverpod-firestore-stream1.appspot.com',
    iosClientId: '215663281164-3hualhirs0hup40n02v7e9tkkp8tnjeo.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.riverpodFirestoreSteam1',
  );
}
